#Title, logo
baseurl: ""
permalink: "/:title/"
title: "Amit Shanbhag"
logo: 'etc/images/favicon/logo.png'
favicon: 'etc/images/favicon/favicon.ico'

#System config

timezone: UTC
locale: en_us
lang: en_us
markdown: kramdown
kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
    disable: false
    input: GFM
sass:
  sass_dir: _sass
  style: :compressed

#analytics
ganalytics: "G-LLE20YGVSB"

#Search config
search_enabled: true
search.heading_level: 1
nav_sort: case_insensitive
exclude: ['bin',"*.sh","*.yml"]

#feed
paginate: 30
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1

#social
disqus: 'disqus-amitshanbhag'
social:
  twitter: https://twitter.com/udakamit
  bluesky: https://bsky.app/profile/amitshanbhag.bsky.social

authors:
  amitshanbhag:
    name: Amit Shanbhag
    email: ashanbh@users.noreply.github.com
    web: https://amitshanbhag.com/
    twitter: https://twitter.com/udakamit
    description: "Amit Shanbhag"
    avatar: 'etc/images/amitshanbhag.png'

# Plugins
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives